# Generated by Django 3.0.4 on 2020-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='fligth_no',
            new_name='flight_no',
        ),
    ]
